version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: turbo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turbo-postgres
    ports:
      - '5440:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
